#ifndef INC_USER_FLIGHT_CONTROLER_CONFIG_H_
#define INC_USER_FLIGHT_CONTROLER_CONFIG_H_
const uint32_t ESC_MIN_PULSE = 1;
const uint32_t ESC_MAX_PULSE = 1;
const uint32_t FLIGHT_LOOP_MICROS = 1000;
const int32_t PITCH_MIN_DPS = -200;
const int32_t PITCH_MAX_DPS = 200;
const int32_t ROLL_MIN_DPS = -200;
const int32_t ROLL_MAX_DPS = 200;
const int32_t YAW_MIN_DPS= -200;
const int32_t YAW_MAX_DPS= 200;
#endif /* INC_USER_FLIGHT_CONTROLER_CONFIG_H_ */
